apiVersion: batch/v1
kind: Job
metadata:
  name: bioassay-import-get-file-info
  namespace: imports
  labels:
    app: bioassay-import
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: bioassay-import-get-file-info
    spec:
      containers:
      - name: bioassay-import-get-file-info
        image: us.gcr.io/aniselect-176223/bioassay-import:latest-master
        resources:
          requests:
            memory: "10G"
          limits:
            memory: "12G"
        imagePullPolicy: Always
        command: ["java","-Xmx10g","-Xms10g", "-jar", "app.jar","get_file_info"]
        volumeMounts:
        - name: nfs
          mountPath: /code/data
        - name: save-file
          mountPath: /saveFile
        envFrom:
        - configMapRef:
           name: bioassay-import
      restartPolicy: Never
      imagePullSecrets:
      - name: anivive-google
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nas-mount-imports
      - name: save-file
        persistentVolumeClaim:
          claimName: pod-save-files-imports